# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ebe8b02200c65433a709129171028595028ad7f6a08cb56ed3bf18c07ce29ba9162c994ab39bb6d5a32b15704e48a6b62b5f6f15f656d0327cb5bd30f59c9f55

test:
  secret_key_base: 737be40df94d5e5af5faa20496139c8495dbc1e20cc75f492bc1f413363d2a84812624a5fff894889bc5239bed74f1ea1c6c4c357b5a81c5f7740614d4eb7962

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
